server:
  port: 8080
  ssl:
    enabled: true
    hsts:
      max-age: 31536000
      include-subdomains: true
      preload: true

spring:
  application:
    name: api-security

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    url: jdbc:mysql://localhost:3306/api-security?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#    username: root
#    password: Zawarudo12!@
    url: jdbc:mysql://student-management-system.crruakemgggf.us-east-1.rds.amazonaws.com:3306/api-security?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: admin
    password: password123$
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

redis:
  host: redis-16989.c14.us-east-1-3.ec2.cloud.redislabs.com
  port: 16989
  password: EqEd3t4jnqQfHw3BV8QnWT2fMs3XvNZQ
  database: 0
  timeout: 1000
  timeToLive: 15

rate-limiter:
  max-number-of-requests: 100
  time-period-for-rate-limit: 2

treblle:
  api-key: HeyANOrCZwEPLKD3ViPhQKSDXJfJMYTg
  project-id: 4CzWWTjm39C5T4SX